### ISSUE TITLE
Ensure `truffle-contract-schema` correctly handles solc output

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/truffle-contract-schema#1]
The output of a single contract from `solc` should be able to be piped directly into `truffle-contract-schema`, and it should return a normalized contract artifact.

`develop` branch

**Comment by tcoulter** [comment]
FYI: Move `solc.js` test from `truffle-contract:develop`

**Comment by gnidan** [comment]
Additionally we want to adhere to the new [standard JSON interface](https://solidity.readthedocs.io/en/develop/using-the-compiler.html#compiler-input-and-output-json-description).
